/*
 * DIO_config.c
 *
 *  Created on: 10 Nov 2022
 *      Author: abdel
 */


#include "DIO_config.h"

// Specify Used Pins
pin_config pin_array[PIN_COUNT] = {
		// Port A
		{PORT_A, PIN_0, OUTPUT, PULLUP_OFF},
		{PORT_A, PIN_1, OUTPUT, PULLUP_OFF},
		{PORT_A, PIN_2, OUTPUT, PULLUP_OFF},
//		{PORT_A, PIN_3, OUTPUT, PULLUP_OFF},
//		{PORT_A, PIN_4, OUTPUT, PULLUP_OFF},
//		{PORT_A, PIN_5, OUTPUT, PULLUP_OFF},
//		{PORT_A, PIN_6, OUTPUT, PULLUP_OFF},
//		{PORT_A, PIN_7, OUTPUT, PULLUP_OFF},
		// Port B
		{PORT_B, PIN_0, OUTPUT, PULLUP_OFF},
		{PORT_B, PIN_1, OUTPUT, PULLUP_OFF},
		{PORT_B, PIN_2, OUTPUT, PULLUP_OFF},
//		{PORT_B, PIN_3, OUTPUT, PULLUP_OFF},
//		{PORT_B, PIN_4, OUTPUT, PULLUP_OFF},
//		{PORT_B, PIN_5, OUTPUT, PULLUP_OFF},
//		{PORT_B, PIN_6, OUTPUT, PULLUP_OFF},
//		{PORT_B, PIN_7, OUTPUT, PULLUP_OFF},
		// Port C
//		{PORT_C, PIN_0, OUTPUT, PULLUP_OFF},
//		{PORT_C, PIN_1, OUTPUT, PULLUP_OFF},
//		{PORT_C, PIN_2, OUTPUT, PULLUP_OFF},
//		{PORT_C, PIN_3, OUTPUT, PULLUP_OFF},
//		{PORT_C, PIN_4, OUTPUT, PULLUP_OFF},
//		{PORT_C, PIN_5, OUTPUT, PULLUP_OFF},
//		{PORT_C, PIN_6, OUTPUT, PULLUP_OFF},
//		{PORT_C, PIN_7, OUTPUT, PULLUP_OFF},
		// Port D
//		{PORT_D, PIN_0, OUTPUT, PULLUP_OFF},
//		{PORT_D, PIN_1, OUTPUT, PULLUP_OFF},
		{PORT_D, PIN_2, INPUT, PULLUP_OFF}
//		{PORT_D, PIN_3, OUTPUT, PULLUP_OFF},
//		{PORT_D, PIN_4, OUTPUT, PULLUP_OFF},
//		{PORT_D, PIN_5, OUTPUT, PULLUP_OFF},
//		{PORT_D, PIN_6, OUTPUT, PULLUP_OFF},
//		{PORT_D, PIN_7, OUTPUT, PULLUP_OFF}
};
